mappings:
  CssColorChart: Sunnysideup\Typography\Api\CssColorChart
  TypographyTestPageController: Sunnysideup\Typography\TypographyTestPageController
  TypographyTestForm: Sunnysideup\Typography\Forms\TypographyTestForm
