---
Name: 'TypographyRoutes'
After: framework
Only:
  environment: dev
---
SilverStripe\Control\Director:
  rules:
    'typo//$Action/$ID/$OtherID/$Version': Sunnysideup\Typography\TypographyTestPageController
---
Name: 'TypographyRoutes'
After: framework
Only:
  environment: test
---
SilverStripe\Control\Director:
  rules:
    'typo//$Action/$ID/$OtherID/$Version': Sunnysideup\Typography\TypographyTestPageController
