---
Name: 'TypographyRoutes_DEV_AND_TEST'
After: framework
Only:
  environment:
    - dev
    - test
---
SilverStripe\Control\Director:
  rules:
    'typo//$Action/$ID/$OtherID/$Version': Sunnysideup\Typography\TypographyTestPageController
---

